=== 345696340/hxht/springmvc3/target/classes/productionConf.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT replyconf (unicomconf,productconf+)>
<!ELEMENT unicomconf (ipaddr,addrport,spNodeid,spListenPort,spUserName,spPassword,smgUserName,smgPassword)>
<!ELEMENT ipaddr (#PCDATA)>
<!ELEMENT addrport (#PCDATA)>
<!ELEMENT spNodeid (#PCDATA)>
<!ELEMENT spListenPort (#PCDATA)>
<!ELEMENT spUserName (#PCDATA)>
<!ELEMENT spPassword (#PCDATA)>
<!ELEMENT smgUserName (#PCDATA)>
<!ELEMENT smgPassword (#PCDATA)>
<!ELEMENT productconf (name,spnumber,servicetype,transmitip,destport)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT spnumber (#PCDATA)>
<!ELEMENT servicetype (#PCDATA)>
<!ELEMENT transmitip (#PCDATA)>
<!ELEMENT destport (#PCDATA)>

=== 345696340/hxht/springmvc3/target/classes/productionConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE replyconf SYSTEM "productionConf.dtd">
<replyconf>
	<unicomconf>
		<ipaddr>127.0.0.1</ipaddr>
		<addrport>8704</addrport>
		<spNodeid>3000091444</spNodeid>
		<spListenPort>8904</spListenPort>
		<spUserName>openet</spUserName>
		<spPassword>openet</spPassword>
		<smgUserName>openet</smgUserName>
		<smgPassword>openet</smgPassword>
	</unicomconf>
	<productconf>
		<name>DXAC</name>
		<spnumber>1062836516</spnumber>
		<servicetype>DXAC</servicetype>
		<transmitip>192.168.0.6</transmitip>
		<destport>7750</destport>
	</productconf>
	<productconf>
		<name>WEBAC</name>
		<spnumber>1062836516</spnumber>
		<servicetype>WEBAC</servicetype>
		<transmitip>192.168.0.6</transmitip>
		<destport>7750</destport>
	</productconf>
</replyconf>
